      SUBROUTINE DOCHEMI(FVALI,N,USOLI,OTYPE,DENCOR)
      
!      INCLUDE 'parameters_add_CO2.txt'xx
      INCLUDE '../INCLUDECHEM/parNZ.inc'
      INCLUDE '../INCLUDECHEM/parNQ_NQT.inc'
      INCLUDE '../INCLUDECHEM/parNEQ_LDA.inc'
      INCLUDE '../INCLUDECHEM/parNR.inc'
      INCLUDE '../INCLUDECHEM/parNSP_NSP1_NSP2.inc'
      INCLUDE '../INCLUDECHEM/parNMAX.inc'
      INCLUDE '../INCLUDECHEM/parNF.inc'
      INCLUDE '../INCLUDECHEM/comNBLOK.inc'  

      INCLUDE '../INCLUDECHEM/comABLOK.inc' !NEW:JTROP DEL:PMOD
      INCLUDE '../INCLUDECHEM/comBBLOK.inc' 
      INCLUDE '../INCLUDECHEM/comCBLOK.inc' !ZTROP 
      INCLUDE '../INCLUDECHEM/comFBLOK1.inc' 
      INCLUDE '../INCLUDECHEM/comGBLOK.inc'
      INCLUDE '../INCLUDECHEM/comSATBLK.inc' ! for H2OSAT
      INCLUDE '../INCLUDECHEM/comSULBLK.inc'
      INCLUDE '../INCLUDECHEM/comLTBLOK.inc' !for ZAPNO
      INCLUDE 'INCLUDECHEM/isotope_name.inc'
c      PARAMETER(NQI=31, NQI1=NQI+1, NSLS=38) 
c      PARAMETER(NRI=353, NSPI=78, NSPI1=NSPI+1, NSPI2=NSPI+2,NMAXI=70)

      DIMENSION FVALI(NQI,NZ),XPI(NZ),XLI(NZ),USOLI(NQI,NZ)
      REAL ZAPO2I(JTROP),LIGHTNO2I,DENCOR,GPPI,GPPIC
C
      COMMON/RATESIS/RAINGCI(NQI,NZ),DDI(NQI,NZ),DKI(NQI,NZ),
     2  DUI(NQI,NZ),DLI(NQI,NZ),DHUI(NQI,NZ),DHLI(NQI,NZ),HIZ(NQI,NZ),
     3 VDEPI(NQI),RATI(NRI)
     

      COMMON/NIBLOK/LH2CQ,LQ,LH2Q,LQH,LHOQ,LH2OQ,LO2Q,LOQO,LCQ,LCH3OQH,
     2  LCH3QOH,LCH3OQ,LCH3QO,LN2Q,LNQ,LNOQ,LHNOQ,LHNO2Q,
     3  LHOQNO2,LHO2NOQ,LNO2Q,LN2O4Q,LN2QO4,LOQ,
     4  LSQ,LSOQ,LH2SO3Q,LHSQ,LCOQ,LHQO,LHQONO2,LQ1D, 
     5  LH3CQ,LHCQ,LSO1Q,LSO3Q,LHSO2Q,LSO2Q,LIH2CO,LIO,LIH2O,LIOH,
     6  LIHO2,LIH2O2,LIO3,LIH,LIH2,LICH4,LICO,LICH3OOH,LICH3O2,LIN2O,
     7  LINO,LINO2,LIHNO3,LIHO2NO2,LINO3,LIN2O5,LIO2,LIH2S,LIHS,LISO,
     8  LISO2,LIHSO,LICO2,LIO1D,LICH21,LICH23,LICH3,LIH3CO,LIHCO,LIN,
     9  LIS,LISO21,LISO23,LIHSO3,LISO3,LIN2
      INTEGER N


      DO I=1,NQI
       DO J=1,NZ
        FVALI(I,J) = 0.
       ENDDO
      ENDDO 
      DO 1 I=1,NQI
      DO 1 J=1,NZ
   1  DIZ(I,J) = USOLI(I,J) * DEN(J)

C
C   THIS SUBROUTINE DOES THE CHEMISTRY BY CALLING CHEMPLI.  PHOTO-
C ***** SOLVE FOR THE PHOTOCHEMICAL EQUILIBRIUM SPECIES *****
C 

c      print *,'NQI1 =', NQI1  
c      print *,'NSLS =', NSLS                                            
      DO 3 I=NQI1,NSLS                                     
      CALL CHEMPLI(XPI,XLI,I,OTYPE) 
c      print *,' I1 =', I 
c      print *,'XPI(I) =',XPI(I) 
c      print *,'XLI(I) =',XLI(I)                             
      DO 3 J=1,NZ                                         
   3  DIZ(I,J) = XPI(J)/XLI(J)
c   
      DO 4 I=1,NQI
      CALL CHEMPLI(XPI,XLI,I,OTYPE)
c     print 2000,I,(XPI(J),XLI(J),J=1,NZ,NZ-1)
c2000 format('I =',I3,1p4e10.3) 

C-AP
      
      DO 4 J=1,NZ
      XLJ = XLI(J) + RAINGCI(I,J)
      FVALI(I,J) = XPI(J)/DEN(J) - XLJ*USOLI(I,J)
      YPI(I,J) = XPI(J)
   4  YLI(I,J) = XLJ


CCCCCCCCC
C-PL ADD FOR H2O QUESTION WHETHER WE NEED ! PART 06/03
C-AP ***********************************************
C   ZERO OUT H2O TERMS IN THE TROPOSPHERE AND INCLUDE LIGHTNING
C   PRODUCTION OF NO, O2, AND CO.  (MUST INCLUDE CO IN ORDER TO
C   BALANCE THE HYDROGEN BUDGET)
C-AS This is a leftover of the low O2, high CO2 version of the 
c    photochemical code, all the commented lines on this do loop
c    are not nedeed for this highO2 version of the code


      DO J=1,JTROP
      FVALI(LH2Q,J) = 0.
      SCALE = RAIN(J)/RAIN(1)
C-JL SCALE WITH DENCOR 
      ZAP = ZAPNO * SCALE*DENCOR
      FVALI(LNQ,J) = FVALI(LNQ,J) + ZAP/DEN(J)
      YPI(LNQ,J) = YPI(LNQ,J) + ZAP
C-PL ONLY CONSIDER N2+O2=2NO  
      FVALI(LOQ,J) = FVALI(LOQ,J) - 2.*ZAP/DEN(J)   !0.5
      YLI(LOQ,J) = YLI(LOQ,J) + 2.*ZAP/DEN(J) !0.5  
      ZAPO2I(J) = 2.*ZAP/DEN(J) !0.5
      enddo
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

C  VOLCANIC OUTGASSING OF SOQ
C    Note: PRSO2 = 3.5E9, distributed over lower 10 km.
      PRSO2 = 2.*3.5E9/1.E6*DENCOR !C-PL 06/13 you need times two for SOQ HERE
!      PRH2S = 3.5E8/1.e6 !h2s
      JTEN = 1.E6/DELZ + 0.01
      DO 351 J=1,JTEN
      FVALI(LSOQ,J) = FVALI(LSOQ,J) + PRSO2/DEN(J)
!      FVALI(LIH2S,J)= FVALI(LIH2S,J) + PRH2S/DEN(J)
!      YP(LIH2S,J) = YP(LIH2S,J) + PRH2S
 351  YPI(LSOQ,J) = YPI(LSOQ,J) + PRSO2
C
C-PL ADD FOR H2O QUESTION WHETHER WE NEED HERE
CQUESTION WHETHER WE NEED ! PART 06/03
C   H2O CONDENSATION IN THE STRATOSPHERE
C   (RHCOLD IS THE ASSUMED RELATIVE HUMIDITY AT THE COLD TRAP
      RHCOLD = 0.1
      JT1 = JTROP + 1
      CONFAC = 1.6E-5
      DO 13 J=JT1,NZ
      H2OCRT = RHCOLD * H2OSAT(J)
      IF (USOL(LH2O,J) .LT. H2OCRT) GO TO 13
C-JL CHANGE USOLI(H2Q) TO H2O BECAUSE THE DENCOR SHOULDN'T DECREASE THE LOSS
C    FREQUENCY 
      CONDEN(J) = CONFAC * (USOL(LH2O,J) - H2OCRT)*DENCOR
C-JL NOT MUTIPLY CONDEN(J) OF MAIN CODE'S WATER BY DENCOR 
      FVALI(LH2Q,J) = FVALI(LH2Q,J) - CONDEN(J)!*DENCOR 
  13  CONTINUE

!QUESTION whether need this?06/11 won't change the result too much
! so comment out. Discuss with Jim
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C-PL eliminate fei O2/CO2  07/2019
!      CORRO2 =  2.*1.7E14/1.E5!2.2521E12/1.E5
      GPPI = 2.* GPPOXY/1.E5 /10.*DENCOR !Divide GPP into 10 layers 
      GPPIC= 2.* GPPCDE/1.E5 /10.*DENCOR
C REMOVED

C       PRINT *,'GGPI =',GPPI 
C       PRINT *,'GPPIC =',GPPIC 

C      DO J=1,10
C      FVALI(LOQ,J) = FVALI(LOQ,J) - GPPI/DEN(J)
C      YL(LOQ,J) = YL(LOQ,J) + GPPI/DIZ(LOQ,J)
C      END DO
C INJECTED
       DO J=1,10
       FVALI(LOQ,J) = FVALI(LOQ,J) + GPPI/DEN(J)
       YPI(LOQ,J) = YPI(LOQ,J) + GPPI

       FVALI(LCOQ,J) = FVALI(LCOQ,J) + GPPIC/DEN(J)
       YPI(LCOQ,J) = YPI(LCOQ,J) + GPPIC


C-JL INJECT NQ
C      FVALI(LNQ,J) = FVALI(LNQ,J) + NOFLUX/DEN(J)
C      YPI(LNQ,J) = YPI(LNQ,J) + NOFLUX 
       END DO
C      PRINT *,'H2SO4S(J) =',H2SO4S
      CONFAC = 1.6E-5
      PSO4AER = 0.0
      DO 14 J=1,NZ 
C-JL DIVIDE BY DENCOR 
      CONSO4(J) = CONFAC * (USOLI(LH2SO3Q,J)/DENCOR - (H2SO4S(J)*4.))
      CONSO4(J) = AMAX1(CONSO4(J),0.)
C-JL  MUTIPLY BY DENCOR
      FVALI(LH2SO3Q,J) = FVALI(LH2SO3Q,J) - CONSO4(J)*DENCOR
      YLI(LH2SO3Q,J) = YLI(LH2SO3Q,J) + CONFAC

C-JL RED FLAG:DIDN'T CHANGE THE WRONG LOGIC BELOW AS IT JUST FOR THE BUDGETING
C-JL NEED TO REVISIT LATER 
C-------------------------
      IF((H2SO4S(J)*4.).GT.USOLI(LH2SO3Q,J)) THEN !C-PL WHEN OVER SATURATION
      YPI(LH2SO3Q,J) = YPI(LH2SO3Q,J) + 0.0 
      ELSE
      YPI(LH2SO3Q,J) = YPI(LH2SO3Q,J) + CONFAC*4.*H2SO4S(J)*DEN(J)
      PSO4AER = PSO4AER + CONSO4(J)*DEN(J)*1.e5
      END IF
  14  CONTINUE

C-AP
C   SPECIAL TREATMENT FOR H2O AND NO
C-PL CALCULATE TP/L(H2O) IN TROPOSPHERE AND 
      TPH2OI = 0.
      TLH2OI = 0.
     
      DO J=1,JTROP
      TPH2OI = TPH2OI + YPI(LH2Q,J)*1.e5
      TLH2OI = TLH2OI + YLI(LH2Q,J)*DIZ(LH2Q,J)*1.e5
      END DO
C-PL GET RID OF 218-224 IN ORDER TO GET RIGHT TP/TL(H2O)
!      DO 5 J=1,NZ
!      IF(Z(J).GT.ZTROP) GO TO 7     
!      FVALI(LH2Q,J) = 0.
!      YP(LH2Q,J) = 0.
!      YL(LH2Q,J) = 1.E-99  
!   7  CONTINUE
!   5  CONTINUE

      IF(N.LT.1) RETURN
  
      DO 8 I=1,NQI
      TPI(I) = 0.
      TLI(I) = 0.
      DO 8 J=1,NZ
      TPI(I) = TPI(I) + YPI(I,J)*1.e5
      TLI(I) = TLI(I) + YLI(I,J)*DIZ(I,J)*1.e5
   8  CONTINUE


C-PL CALCULATE TL(O2) BY LIGHTNING
      LIGHTNO2I = 0.
      DO J=1,JTROP
      LIGHTNO2I = LIGHTNO2I + ZAPO2I(J)*DIZ(LOQ,J)*1.e5

      END DO
c      print *
c      print *,'Made it to the end of DOCHEM!'
c      stop
      RETURN
      END
