c NSP - Number of chemical species
c NSP1 - chemical species plus hv
c      PARAMETER(NSP=55, NSP1=NSP+1, NSP2=NSP+2)

c in May 7, 2019, JL rip off cl species 
      PARAMETER(NSP=44, NSP1=NSP+1, NSP2=NSP+2)

c may 14 2020, JL move isotope parameter here 
      PARAMETER(NQI=31,NQI1=NQI+1, NSLS=38, NMAXI=70)
      PARAMETER(NRI=366, NSPI=78, NSPI1=NSPI+1, NSPI2=NSPI+2)
      PARAMETER(NEQI=NQI*NZ, LDAI=3*NQI+1)
